# Overall Groups and Questions

## Sample groups

1. Workshop attendees where the main population of learners are coming from a medical background.
    1. [Fralin Biomedical Research Institute at VTC](https://research.vtc.vt.edu/)
        - Fall 2020: iTHRIV scholars (n = 2)
        - FBRI faculty members
    2. [Roanoke Higher Education Center](https://www.education.edu/)
        - Fall 2020: Healthcare workshop series (n = 9)
2. Workshop attendees where the main population of learners are students (undergraduate/graduate)
    1. Fall 2020: Undergraduate/graduate Carpentries-inspired class
    2. Students from small modules taught as a part of a university course


- Workshop attendees (this will be a series of convenience samples)
    - What are potential issues and biases with this sample?
- Population will be self-selecting and more likely to be self-motivated
    - Individuals will need to register to attend the workshop or class

## Research Question

What is my actual research question?

1. What are the hurdles biomedical/medical/health professionals have
  with regards to using data for decision making and/or research?
    - Approach this problem from "first principles"
        - They have a question but do not know how to get the data needed
        - They have the data but do not know where to start
    - "The Democratization of Data Science Education"
        - https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1668849?src=recsys

## Hypothesis

These need to be targeted towards learning objectives.

1. Creating learner personas will create better educational content because they will be more tailored to the needs of the students
1. Learning how to program data analysis will allow learners to feel like they can do more with their data (the main goal)
2. Learning basic data literacy and data science skills can empower health workers and be more proactive in making more educated decisions
3. Workshops with an eye towards tidy data principles will better transition students out of a spreadsheet program into programming
4. In-person workshops will help medical professionals curate better data for research
5. In-person workshops will help medical professionals work with data outside of a spreadsheet program

## Approach

1. Create learner personas
    1. Identify learning objectives
    2. Assessments
        - This will identify whether learning objectives are met
        - Will provide concrete examples and data for personas, so they do not become a list of sterotypes
        1. Student self assessment
            - Self assessment will help identify the various personas
        2. Student pre-workshop assessment
        3. Student post-workshop assessment
        4. Student long-term assessment (6 months)
