# Creating Personas

## Persona Construction

Questions to ask while creating personas (modified from Zagallo 2019):

  1. What are the personas that exist in the student community of health professionals?
  2. What are the similarities and differences in desired student outcomes among personas?
  3. What are the distinctive ways students approach data science, and the situational barriers they encounter?

  Each persona should have

1. The person's general background
2. What they already know
3. What they think they want to do
4. Any special needs they have

Main groups of students {#persona-groups}

- Medical / osteopathic doctors
- Nurses
- MD PhD programs
- Analysis hired to work in the medical field
- Other health professionals (MPH, DVM)

### 6-step creation process (Pruitt and Adlin, 2006)

1. Discuss categories of users
    - What user information is important to examine for product design
      - Here, the product is training material (learning objectives), users are attendees/students
    -  Operating under the framework of situated learning (Lave and Wenger, 1991; Kelly, 2006)
      - What information about students would best aid development of training materials and learning objectives
    - See #persona-groups
    - what are their motivations?
      - what do the students value? what extent do they invest to data literacy/fluency
2. Process data
    - extracting information, themes, and relationships from user data
    - Strauss and Corbin, 2998 interview coding
    - Table 2 in Zagallo 2019 paper: Themes and theme descriptions used to characterize personas
        - These themes can be used for cluster analysis for persona creation
        - Adapted from Zagallo 2019
        1. Knowledge of students
        2. Values: what are important to the students. what should get they get out of it?
        3. Approaches: attitude/opinion re: data fluency and other data practices
        4. Perceived barriers: local/departmental/institutional norms students view as barriers
        5. Desired outcomes: what should the students know after training
3. Identify and create skeletons
    - Skeletons contain relevant data and descriptions that are used to further develop the persona character
    - Use results from step 2 to create personas
    - Use clustering analysis to group participants
4. Evaluate and prioritize skeletons
    - deciding which skeletons will be developed into personas
5. Develop skeletons into personas
    - Coding summaries to identify key traits for each theme
    - Employ alliteration for persona names to increase memorability
    - Use a picture, but they can also trigger biases and preconceptions (Salminen et al, 2019)
6. Validate personas
    - examine whether personas still reflect the real data after undergoing steps 1-5

### Qualative analysis
#### Coding
- Themes
    1. Knowledge of students
    2. Teaching values (need analogy for phd)
    3. Approaches to innovation (need analogy for phd)
    4. Perceived barriers
    5. Desired outcomes

### Cluster analysis
- Several clustering methods exist, and they differ based on the distance metrics used.
    We used methods that combine hierarchical agglomerative cluster analysis
    with chi-square values or squared Euclidian distance
    values and complete or average linkage (DataCamp, Inc., n.d.; Wilks, 2011)
- For cluster analysis, the number of codes should not be greater than the number of individuals who are being clustered (Aldenderfer and Blashfield, 1984)
- multiple cluster analyses with different distance and
linkage algorithms. Each of these methods leads to a dendro-
gram that illustrates possible hierarchical relationships within
the data (Arabie et al., 1996)
- five personas is the
maximum number recommended by Pruitt and Adlin (2006)
-  compared multiple
dendrograms generated by different algorithm measures to
identify common cluster relationships among participant
    - instead of bootstrapping because of low sample size

## Example personas

(Zagallo 2019)

- barriers
expressed by all personas, such as concerns about content cover-
  age or large class sizes with insufficient teaching resources, indi-
  cate problems in departmental, institutional, and disciplinary
cultures (Kezar, 2014; Corbo et al., 2016; Reinholz and Apkar-
            ian, 2018)

### Emma

- Emma likes learning objectives, because they help her organize
the course, but she may not integrate learning objectives into
her classroom practice
- understand the impact of sharing learn-
  ing objectives with students. Doing so increases students’ learn-
  ing (Armbruster et al., 2009), motivation and engagement
(Armbruster et al., 2009; Winkelmes et al., 2016; Reynolds and
  Kearns, 2017), metacognition (Levine et al., 2008), and self-reg-
  ulated use of appropriate study strategies (Simon and Taylor,
                                              2009)
- learn to use evi-
  dence-based pedagogies like case-based learning (Borrego et al.,
                                                   2013) or authentic data-interpretation tasks (Hoskins et al.,
                                                                                                 2007; Round and Campbell, 2013; Zagallo et al., 2016) that
provide real-life problem-solving scenarios
- science is hard but that an opportunity gap exists within the
student population, particularly for women, students of color,
and students from lower socioeconomic status backgrounds
(Eddy et al., 2014; Ballen et al., 2017), and that evidence-based
teaching can help close the opportunity gap (Freeman et al.,
                                             2011; Eddy and Hogan, 2014; Ballen et al., 2017)
- an interest in equity, these facts might help her overcome her
focus on sorting and her concern about the “top” students.

### Ray

- teaching practice is similar to Emma’s, but he more
greatly values connecting to students and gauging their feelings
in real time during class.
- intrinsic interest in relating to students and teach him concrete
ways to cognitively engage students (Chi and Wylie, 2014)
- greatest barrier appears to be how to scale up personal
connections with students in large classes
- emphasize evidence-based techniques that allow Ray to
personally connect with students in large classes, such as using
index cards to learn students’ names and call on students by
name (Tanner, 2011)

### Carmen

- will thrive when given the
chance to work with colleagues to build new lessons that
engage students in scientific practice (e.g., Elliott et al., 2016;
                                        Pelletreau et al., 2018)
- facilitators who lead
change efforts at the department level, such as the departmen-
  tal action teams presented by Corbo and colleagues (Corbo
                                                      et al., 2016), should consider tapping Carmen as a leader.
- persistence with evidence-based teaching and willingness to
tackle barriers could be critical in work that addresses the sys-
  temic structures for recognizing, rewarding, and incentivizing
teaching (Reinholz and Apkarian, 2018)

### Beth

- providing a
curriculum about student interest and motivation (Lovelace
                                                  and Brickman, 2013; Seidel et al., 2015; Jordt et al., 2017).
- only persona who does not express
student motivation and engagement as a PD outcome (Table 3),
even though she reports a lot of frustration with students’ lack
of engagement.
- puts such a heavy burden of learning
on herself that she may have inadvertently taken a lot of the
“fun” out of motivating and engaging students.
- tremendous leadership potential, yet she may be unlikely to
lead because of burnout
